### ISSUE TITLE
Components auto-completion?

### ISSUE THREAD

**Issue by sooqua** [felipeochoa/rjsx-mode#117]
Is it possible to get auto-completion for imported React components?
```js
import Navbar from './components/layout/Navbar';
const App = () => {
  return (
    <div className="App">
      <Nav| /> << NO AUTO-COMPLETION
    </div>
  );
};

**Comment by felipeochoa** [comment]
That's not part of this package. You can use tern or typescript for completions. I'd suggest company mode on the emacs side
