### ISSUE TITLE
re-using parts of rjsx-mode for js.el

### ISSUE THREAD

**Issue by shackra** [felipeochoa/rjsx-mode#118]
I'm currently using the built-in Javascript support that comes with Emacs 27.x, and I was missing the context-sensitive insertion of `<` or `</>`, so I extracted `rjsx-electric-lt` and added some test cases and put it here: https://gitlab.com/shackra/colibri

I was studying `rjsx-delete-creates-full-tag` and it seems I would need to come with a code that solves the same problem in a different fashion, when I come with it I would like to contribute to js.el.

My question is: Would you provide permission to re-use the extracted `rjsx-electric-lt` code to the Javascript support on Emacs?

my email to emacs-devel about this: https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00282.html

**Comment by shackra** [comment]
hello?

**Comment by felipeochoa** [comment]
Yes I've authorized elsewhere on this issue tracker

**Comment by shackra** [comment]
Sorry for bothering you but the maintainers of Emacs says:

> Thanks, but we need that agreement sent By Felipe to this mailing
> list, so that we could quote it in the commit log message.

you can reply to that email visiting it here https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00437.html
