### ISSUE TITLE
[Feature request]  highlightning undefined variables

### ISSUE THREAD

**Issue by C0DK** [felipeochoa/rjsx-mode#121]
I know this is a massive feature, but I'm having problems seeing undefined variables as well as autocompleting variables in general. Maybe i should switch to ts instead, as it seems there are stronger emacs modules for that, but I'd still say that it is missing here.. 

You can always leave the issue open forever.

**Comment by knobo** [comment]
I use flycheck with eslint

**Comment by felipeochoa** [comment]
I personally use tide for completions, and there's also tern. For undefined variables there's a js2 setting to highlight those which will also work in rjsx

**Comment by C0DK** [comment]
Oic. thank you! :) i'll look into that.
