### ISSUE TITLE
How to highlight tags in jsx

### ISSUE THREAD

**Issue by ivanddm** [felipeochoa/rjsx-mode#124]
In the readme it says that it is possible to "Highlighting JSX tag names and attributes (using the rjsx-tag and rjsx-attr faces)". How can I do that?

I want to highlight matching tags by changing the background, foreground of the tag. In web-mode I accomplish this with `(setq web-mode-enable-current-element-highlight t)`

Thanks in advance.

**Comment by felipeochoa** [comment]
The highlighting mentioned just allows static tag highlighting (i.e., in contrast to js2 mode which leaves everything with the default face). We don't have support for dynamic tag highlighting
