### ISSUE TITLE
Type statement in Backticks destroys syntax highlighting and indentation

### ISSUE THREAD

**Issue by m1cm1c** [felipeochoa/rjsx-mode#131]
If a type statement (e.g. `as number`) occurs in backticks, the syntax highlighting breaks from a point shortly after until the end of the buffer. Furthermore, indentation sometimes breaks. I have yet to figure out under what circumstances indentation breaks but here is a minimal example of how to get the syntax highlighting to break:

```
if(true) {
  const a = [1, 'a'];
  console.log(`${Math.max((a[0] as number), 5)}`);
} else {
  console.log('b');
}
```

It looks like this:
![image](https://user-images.githubusercontent.com/11382432/149174281-b6346f15-f0c2-459c-863f-66e77f371f75.png)

**Comment by felipeochoa** [comment]
RJSX does not support types -- this is only for plain JSX
