### ISSUE TITLE
Angle brackets cause cascading failure in syntax highlighting

### ISSUE THREAD

**Issue by m1cm1c** [felipeochoa/rjsx-mode#133]
Minimal example:

```
export default function Foo() {
  const foo = (event : React.ChangeEvent<HTMLInputElement>) => {
    console.log(event);
  };

  const bar = () => {
    console.log('bar');
  };
}
```

The code is rendered in red from the element containing the angle brackets until the end of the buffer:
![image](https://user-images.githubusercontent.com/11382432/149921345-231b2685-6c2c-450b-bb1a-9ffe5ba7d51c.png)

**Comment by felipeochoa** [comment]
RJSX does not support type annotations
