### ISSUE TITLE
What do all the underlines mean? Any way to disable?

### ISSUE THREAD

**Issue by cheryllium** [felipeochoa/rjsx-mode#136]
A lot of the code is underlined and I don't understand what this means. Is there a way to disable this? 

![image](https://github.com/felipeochoa/rjsx-mode/assets/5027241/070456c6-c3b5-47dd-8c62-da62b642414d)

**Comment by felipeochoa** [comment]
It looks like those are warnings from js2 about places where a semi colon should be. You can disable it using [`js2-strict-missing-semi-warning`](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L316)

**Comment by felipeochoa** [comment]
It looks like those are warnings from js2 about places where a semi colon should be. You can disable it using [`js2-strict-missing-semi-warning`](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L316)
