### ISSUE TITLE
Workaround to enable flycheck eslint checker

### ISSUE THREAD

**Issue by z4139jq** [felipeochoa/rjsx-mode#15]
Locate this line `(flycheck-define-checker javascript-eslint` in **flycheck.el**(usually in ~/.emacs.d/elpa/flycheck-30/),
1. in the flycheck-define-checker call, change:
`  :modes (js-mode js-jsx-mode js2-mode js2-jsx-mode js3-mode)` to:
`  :modes (js-mode js-jsx-mode js2-mode js2-jsx-mode js3-mode rjsx-mode)`
2. `byte-recompile-file` flycheck.el
3. reload flycheck.el

**Comment by ustun** [comment]
Thanks. Another way to find `flycheck.el` is to do via M-x find-library , then selecting flycheck

**Comment by felipeochoa** [comment]
Thanks both -  is there anything we can add to rjsx to support this out of the box? How does flycheck store the major-mode/checker pairings?


-Felipe






On Sun, Nov 13, 2016 at 8:36 PM +0100, "Ustun Ozgur" <notifications@github.com> wrote:












Thanks. Another way to find flycheck.el is to do via M-x find-library , then selecting flycheck
