### ISSUE TITLE
Fails to load after Flycheck is loaded

### ISSUE THREAD

**Issue by lunaryorn** [felipeochoa/rjsx-mode#17]
Since 86549c1f92b90ae0eb408a85a861c082dfbcbcf5 rjsx-mode fails to load after Flycheck is loaded (irrelevant parts elided):

```
Debugger entered--Lisp error: (void-function \(setf\ flycheck-checker-get\))
  \(setf\ flycheck-checker-get\)((rjsx-mode js-mode js-jsx-mode js2-mode js2-jsx-mode js3-mode) javascript-eslint modes)
  …
```

The cause is a miscompiled `push` form introduced in 86549c1f92b90ae0eb408a85a861c082dfbcbcf5.  In a clean session—which package.el uses when compiling asynchronously—Flycheck isn't loaded when the body of `with-eval-after-load` is compiled `flycheck` isn't loaded, so `push` doesn't have the GV setter definition for `flycheck-checker-get` in scope and thus doesn't expand to a proper `setf` call.

Speaking as Flycheck's maintainer I'd also like to point out that it's not how we prefer Flycheck's API to be used in 3rd party packages.

Why not open a pull request for Flycheck to directly add rjsx-mode to our syntax checker definitions?

**Comment by felipeochoa** [comment]
Thanks for the heads up. I'd love to just add rjsx-mode to flycheck, but I was putting together [a PR](https://github.com/felipeochoa/flycheck/commit/1d21040199c61c94f3cafd68965070737a752cfe), but am on Windows and could not get the (extensive) environment set up for testing the changes.

Not sure how I missed `flycheck-add-mode` when I was looking around earlier -- is that safe to use in `eval-after-load`?

**Comment by lunaryorn** [comment]
@felipeochoa Please just go ahead and open the PR anyway… we've got Travis CI in place, and are happy to test your changes manually if you can't :relaxed:

`flycheck-add-mode` would be safe to use, but we'd really love to support your mode out of the box :blush:

**Comment by felipeochoa** [comment]
Thanks, just submitted flycheck/flycheck#1161 -- I'll remove this nasty hack from here now.
