### ISSUE TITLE
bad function rjsx-electric-lt

### ISSUE THREAD

**Issue by s-kostyaev** [felipeochoa/rjsx-mode#18]
If I press `<` in `rjsx-mode` emacs stop responding to any keypresses and eat my RAM (I kill it with SIGKILL after 4,1 GB). Maybe it's infinite loop.

**Comment by s-kostyaev** [comment]
For now I use emmet-mode as workaround and don't insert `<` manually.

**Comment by felipeochoa** [comment]
Which version of rjsx are you using? There are no loops in `rjsx-electric-lt`, but it does call `looking-back` (conservatively, but still) which can be a hog. Can you provide a sample where you run into this issue?

In the meantime, you can use `(define-key rjsx-mode-map "<" nil)` to disable the keybinding.

**Comment by s-kostyaev** [comment]
> Which version of rjsx are you using?

20161115.456

> Can you provide a sample where you run into this issue?

```jsx
import React from 'react';
 
class PhoneCall extends React.Component {
  render() {
    return (
      <div className="phone-call">
        <h4 className="call-SID">
          {"Call SID: " + this.props.callSid}
        </h4>
        <h4 className="to-number">
          {"To: " + this.props.to}
        </h4>
        <h4 className="from-number">
          {"From: " + this.props.fromNumber}
        </h4>
        <h4 className="date-updated">
          {"Call Status: " + this.props.callStatus}
        </h4>
      </div>
    );
  }
};
```
When I try to write first `<div>` emacs start eating my RAM.

> In the meantime, you can use (define-key rjsx-mode-map "<" nil) to disable the keybinding.

I know it, thanks.

**Comment by felipeochoa** [comment]
Have you tried running `rjsx` in a `-Q` emacs session? I'm still unable to reproduce the problem

**Comment by s-kostyaev** [comment]
I can't reproduce this problem in `-Q` session. Sorry for wasting your time. I will try to inspect my config.

**Comment by felipeochoa** [comment]
No worries thanks for checking

**Comment by s-kostyaev** [comment]
Problem was in fci-mode.
