### ISSUE TITLE
can rjsx-mode support 24.3?

### ISSUE THREAD

**Issue by redguardtoo** [felipeochoa/rjsx-mode#21]
as title.

**Comment by felipeochoa** [comment]
`rjsx` uses the new advice system to patch the `js2` parser, so not easily. I imagine there could be a way to conditionally use one advice system or the other, but it's not something I'm going to write. I might consider a patch for this, depending on the perceived maintenance burden it adds.

**Comment by redguardtoo** [comment]
what about using old advice system?

**Comment by felipeochoa** [comment]
Is there a deprecation plan on that? Does it add any overhead on 24.4 and later?

**Comment by redguardtoo** [comment]
I think advice will stay for a very long time. Since some notable plugins are dependent on it (evil, for example).

**Comment by felipeochoa** [comment]
Makes sense. PR welcome!

**Comment by felipeochoa** [comment]
Closing this given lack of activity. Emacs 24.4 was released in October 2014, so it's coming up on 3 years
