### ISSUE TITLE
Can emmet mode be integrated with rjsx-mode?

### ISSUE THREAD

**Issue by sebasmagri** [felipeochoa/rjsx-mode#23]
Is it possible to integrate emmet-mode with rjsx-mode from configuration? Would it be considered to be included in the development pipeline?

**Comment by felipeochoa** [comment]
I'm not familiar with emmet-mode. What is required for the integration? It would never be baked into rjsx, but if there are certain hooks or config variables that need to exposed we could do that.

**Comment by felipeochoa** [comment]
@sebasmagri I'm closing this issue since I haven't heard from you, but feel free to re-open if you have more thoughts on this.

**Comment by sandric** [comment]
@sebasmagri `(add-hook 'rjsx-mode-hook 'emmet-mode)` if thats what you asked for
