### ISSUE TITLE
Silence warning about missing optional semicolon

### ISSUE THREAD

**Issue by febeling** [felipeochoa/rjsx-mode#25]
Is it possible to turn off warnings about the missing optional semicolons?

Turning it off for all semicolons, not just optional ones would be an acceptable approximation, as far as I'm concerned.

**Comment by felipeochoa** [comment]
This is inherited from `js2`, but the config you're looking for is `js2-strict-missing-semi-warning` (set it to nil). I don't use it myself, but my understanding is that it still warns for non-optional semicolons

**Comment by febeling** [comment]
Awesome. And thanks for the blazingly quick answer!
