### ISSUE TITLE
Add support for flowtype

### ISSUE THREAD

**Issue by juvasquezg** [felipeochoa/rjsx-mode#26]
Hi,

I use rjsx-mode for my projects. I am learning React-Native, I write flow/jsx [flow](https://flowtype.org/)
but the sintax is not not recognized, please look [emacs-flow-jsx](https://github.com/omouse/emacs-flow-jsx), I can combine the two solutions?

Thank you so much

**Comment by felipeochoa** [comment]
Unfortunately I don't think it's possible to combine these two modes. Getting proper flow syntax highlighting will require changes upstream. See mooz/js2-mode#224
