### ISSUE TITLE
indentation of component attributes

### ISSUE THREAD

**Issue by redguardtoo** [felipeochoa/rjsx-mode#28]
Current behavior:
```bash
<MyComp attr1=v1
        attr2=v2
        attr3=v3 />
```

I expect:
```bash
<MyComp attr1=v1
    attr2=v2
    attr3=v3 />
```

The reason is simple, in refactoring, we may use different component name but same attributes. The second style produces smaller diff.

I'm fine to keep the current indentation style by default. But it would be great if there were some flag to switch to second style.

**Comment by felipeochoa** [comment]
Per the README, indentation issues should be reported upstream. For JSX components, it is `sgml-mode` that handles the indentation. You should look there to see if there are any customizations possible or request the enhancement if not.

**Comment by redguardtoo** [comment]
Thanks, looks I need upgrade to Emacs 25. https://github.com/mooz/js2-mode/issues/291
