### ISSUE TITLE
used as generic linter

### ISSUE THREAD

**Issue by bounceme** [felipeochoa/rjsx-mode#29]
https://github.com/bounceme/rjsx-compile makes use of this mode as a "compiler" plugin (vim's builtin linting thing). this may be valuable for vim users, but also shows how this can be a kind of generic jsx linter, just letting you know!

**Comment by felipeochoa** [comment]
Very cool, thanks for sharing! You could also try [Evil mode](https://github.com/emacs-evil/evil) and avoid the hassle of running both editors! 😃
