### ISSUE TITLE
Possible to disable electric functionality?

### ISSUE THREAD

**Issue by peterhadlaw** [felipeochoa/rjsx-mode#31]
Is there a way to disable the auto generation of ` />` when creating new tags?

**Comment by felipeochoa** [comment]
`(define-key rjsx-mode-map "<" nil)` should do the trick. You may also want `(define-key rjsx-mode-map (kbd "C-d") nil)`.

**Comment by peterhadlaw** [comment]
Thank you! It conflicts with an eVil binding by the way, that's where this issue came about. I might think about rebinding, but later. `C-d` is taken.

**Comment by felipeluna** [comment]
Can I remap the C-d ?

**Comment by felipeochoa** [comment]
I don't know how evil-mode works, but you can disable it using `(define-key rjsx-mode-map (kbd "C-d") nil)`

**Comment by felipeluna** [comment]
Hi, actually I don't want to disable the `C-d` in rjsx-mode, in fact i really like it. But also I want to use evil-mode, if I could remap the expansion with another key binding would be really helpful. I just had to find which key binding doesn't conflict with evil-mode. Is is possible to remap the expansion functionality?

Thanks

**Comment by felipeochoa** [comment]
Sure just use `(define-key rjsx-mode-map (kbd "NEW-KEYBINDING") 'rjsx-delete-creates-full-tag)`. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Changing-Key-Bindings.html for more details

**Comment by felipeluna** [comment]
Thank you :D

**Comment by nikolas** [comment]
When I add `(define-key rjsx-mode-map "<" nil)` right after my `(add-to-list 'auto-mode-alist '("src\\/.*\\.js\\'" . rjsx-mode))` line, I get this error when Emacs is loaded:

```
Symbol's value as variable is void: rjsx-mode-map
```

**Comment by felipeochoa** [comment]
The README has the updated instructions. You need to wait until `rjsx` is loaded by using:

```elisp
(with-eval-after-load 'rjsx-mode
  (define-key rjsx-mode-map "<" nil)
  (define-key rjsx-mode-map (kbd "C-d") nil))
```

**Comment by nikolas** [comment]
Oh okay, thanks!
