### ISSUE TITLE
minor html inssues

### ISSUE THREAD

**Issue by redguardtoo** [felipeochoa/rjsx-mode#33]
1. indentation
```html
<div
  prop1="3"
  />
```
I think the the last `/>` should not indent two spaces according to the popular coding style

2. I'd rather rjsx not fill the slash character when I insert a new component directive. Many of our components use `this.props.children` (typical in enterprise applications), the auto inserted `/` is real annoying.

**Comment by felipeochoa** [comment]
1. As mentioned in the `README`:

> **Note**: This mode does not add any indentation improvements to the one built into `js-mode`. Please report all identation bugs there

2. Not sure I follow why `this.props.children` clashes with the electric slash, but to disable it just add this to your init file:

```elisp
(with-eval-after-load 'rjsx
  (define-key rjsx-mode-map "<" nil)
  (define-key rjsx-mode-map (kbd "C-d") nil))
```

I've added a note to the README since it's come up before

**Comment by redguardtoo** [comment]
Thanks, I understand issue 1 is sgml-mode problem.
