### ISSUE TITLE
JSX not formatted correctly

### ISSUE THREAD

**Issue by aikeru** [felipeochoa/rjsx-mode#34]
Other editors like WebStorm and VSCode seem to format/understand a fat arrow expression, followed by linebreak, followed by a JSX tag, but rjsx-mode seems to trip on this.
IE:
```
const Bar = () =>
  <div>
    //add a new tag here/hit enter and it is put at the same indentation as div
  </div>
```

Thanks for your excellent work on this mode! I've definitely seen an improvement over the react layer already.

**Comment by aikeru** [comment]
It works fine if wrapping the JSX with parens
```
const Bar = () => (
  <div>
    //add a new tag here and expect it to be formatted correctly
  </div>
)
```
But as this is valid syntax and other tools work fine with it, maybe there is a way rjsx-mode can support it too? :)

**Comment by aikeru** [comment]
Also I would expect when pressing "enter" / "return" after the JSX for the cursor to move to the beginning of the next line. Instead, it continues on the same line.

**Comment by felipeochoa** [comment]
This is an indentation problem. To quote the README:

> **Note**: This mode does not add any indentation improvements to the one built into `js-mode`. Please report all identation bugs there

**Comment by aikeru** [comment]
@felipeochoa apologies and thanks for the response

**Comment by felipeochoa** [comment]
@aikeru, no problem! I find the indentation situation a bit frustrating as well, but haven't been frustrated enough to actually fix it! :smile:
