### ISSUE TITLE
Closing bracket not align according to eslint  (jsx-closing-bracket-location)

### ISSUE THREAD

**Issue by lawreenas** [felipeochoa/rjsx-mode#35]
Hi,
I'm using AirBnB styleguide, and I have problems meeting jsx-closing-bracket-location rule.

Ideally I want my closing tag to be formatted like so:
```
<Hello
  firstName="John"
  lastName="Smith"
/>;
```
However I end up with:
```
<Hello
  firstName="John"
  lastName="Smith"
  />;
```

Maybe someone had this issue and knows a workaround/patch?

**Comment by felipeochoa** [comment]
This is an indentation issue and thus upstream. To quote the README:

> **Note**: This mode does not add any indentation improvements to the one built into js-mode. Please report all identation bugs there

Though to answer your question, yes, this issue has come up before. Fixing it requires adding the option to `sgml-mode`'s indentation logic. Not sure where that effort is ATM, but you should search https://debbugs.gnu.org/

**Comment by lawreenas** [comment]
The workaround I've found is to call eslint --fix on file save which autofixes eslint issues such as this. Its not ideal, but it works.
Here's a package:
https://github.com/aaronjensen/eslintd-fix
