### ISSUE TITLE
File mode specification error: (void-function js2--struct-put)

### ISSUE THREAD

**Issue by meltedice** [felipeochoa/rjsx-mode#41]
**To fix this error, update js2-mode.**

This is not a issue, just a report.

Today I installed rjs-mode, then got the following error in rjsx-mode:
```
File mode specification error: (void-function js2--struct-put)
```

This is due to calling js2-mode's new function `js2--struct-put`.
And I already installed js2-mode some months ago.
(My installed js2-mode didn't have `js2--struct-put` yet)

js2-mode added `js2--struct-put` function at:
```
commit 97d27d664aed3aaf4332358fd805f64694c53436
Date:   Thu May 4 04:46:38 2017 +0300
```

rjsx-mode added `js2--struct-put` call at:
```
commit 1a7f75b2b6674899aa70fc7961969df6098abfb9
Date:   Mon Jul 10 16:06:37 2017 +0200
```

Both are new.
So better to add dependency notice in README.md?
(like "Update js2-mode before install rjsx-mode")

Thank you for developing rjsx-mode!

**Comment by felipeochoa** [comment]
Hi. Thanks for the report. I thought I'd bumped the version of `js2` that was required, but perhaps I put the wrong number on. Is there a better `js2` version number to include?

**Comment by meltedice** [comment]
Now I found following in rjx-mode.el. I think this is correct.
```
;; Package-Requires: ((emacs "24.4") (js2-mode "20170504"))
```

But maybe js2-mode forgot to bump version.
Or still in development?
https://github.com/mooz/js2-mode/blob/master/js2-mode.el
```
;; Version: 20170116
```

(el-get ignored Package-Requires or I missed warning message.)

Thank you for your quick reply.

**Comment by felipeochoa** [comment]
Based on #42, I think this is only an issue with the stable release. I'm going to close this issue in favor of that one, but thanks for bringing this up!
