### ISSUE TITLE
Evil mode

### ISSUE THREAD

**Issue by celso-henrique** [felipeochoa/rjsx-mode#43]
Deleting the slash in a self-closing tag does not insert a closing tag when using evil mode.

**Comment by felipeochoa** [comment]
The function you're looking for is `rjsx-delete-creates-full-tag`. It is bound in `rjsx-mode-map` to `C-d`, but as I understand it, `evil` overrides that definition. You'll have to bind it to whatever key you use for deleting, or advise the evil command for deleting. Also see #31 

I'm not sure if something like this would work, but another option would be to call `rjsx-delete-creates-full-tag` from a `post-command-hook`. You'd have to use some heuristic to guess whether the last deleted character was a self-closing slash.

**Comment by gone** [comment]
I was able to get this working with:

```
  (defun my/rjsx-init ()
    (interactive)
    (add-to-list 'spacemacs--dap-supported-modes 'rjsx-mode)
    (define-key rjsx-mode-map (kbd "C-d") 'rjsx-delete-creates-full-tag)
    (evil-define-key '(normal insert) rjsx-mode-map
      (kbd "C-d") 'rjsx-delete-creates-full-tag)
    (evil-define-key 'normal rjsx-mode-map
      (kbd "x") 'rjsx-delete-creates-full-tag))
  (add-hook 'rjsx-mode-hook 'my/rjsx-init 'append)
```
