### ISSUE TITLE
Update license to GPL

### ISSUE THREAD

**Issue by notetiene** [felipeochoa/rjsx-mode#47]
This project uses significant parts of the [js2-mode](https://github.com/mooz/js2-mode) package.  The js2-mode package is licensed under the [GPLv3](https://github.com/mooz/js2-mode/blob/master/LICENSE) by the Free Software Foundation.

According to the license terms, this project is _de jure_  subject to the GPLv3 license.  Saying otherwise would be misleading.  See: [If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license?
](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL)

Please update the license to clear confusion that may arise.

**Comment by felipeochoa** [comment]
Hi @notetiene, all the code in `rjsx-mode` is original, except for the `js2-tests`, which is licensed as GPLv3. Since the code here is original, the only requirement, as per your FAQ reference is that the license be "compatible with the GPL". This project's license (the MIT/Expat License) is [explicitly stated to be GPLv3 compatible](https://www.gnu.org/licenses/license-list.html#Expat)

**Comment by notetiene** [comment]
While I strongly disagree with your interpretation of "original code", I
may need to clarify that position with Emacs Lisp. Let me consult a lawyer
and I'll respond back to you.

Le 2017-09-22 02:25, "Felipe" <notifications@github.com> a écrit :

Hi @notetiene <https://github.com/notetiene>, all the code in rjsx-mode is
original, except for the js2-tests, which is licensed as GPLv3. Since the
code here is original, the only requirement, as per your FAQ reference is
that the license be "compatible with the GPL". This project's license (the
MIT/Expat License) is explicitly stated to be GPLv3 compatible
<https://www.gnu.org/licenses/license-list.html#Expat>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/felipeochoa/rjsx-mode/issues/47#issuecomment-331361468>,
or mute the thread
