### ISSUE TITLE
C-d not available in evil mode

### ISSUE THREAD

**Issue by allforabit** [felipeochoa/rjsx-mode#51]
By default "c-d" is not available in evil-mode as it's bound to another shortcut and so `rjsx-delete-creates-full-tag` is not available. I rebound it to ">" instead and this seems to work quite well. Perhaps this could work as an alternative to the "c-d" shortcut?

**Comment by felipeochoa** [comment]
So now `>` is self-inserting, except when point is at a self-closing slash? I like the idea a lot, and is a lot cleaner than re-binding `C-d`.

**Comment by allforabit** [comment]
Yes exactly, the `rjsx-delete-creates-full-tag` function takes care of checking the context. Here's the binding I made:
`(define-key rjsx-mode-map ">" 'rjsx-delete-creates-full-tag)`

**Comment by felipeochoa** [comment]
I haven't tried it, but I suspect you'll run into issues with that binding if you try to input ">" as a greater-than sign rather than a JSX delimiter. I've pushed a proper binding of this in the latest master, which should be on MELPA in a few hours

**Comment by allforabit** [comment]
Thank you, yes I hadn't thought of thought. Your solution looks great and will work perfectly for my purposes.
