### ISSUE TITLE
JSX tags not working with js2-highlight-vars

### ISSUE THREAD

**Issue by felipeochoa** [felipeochoa/rjsx-mode#54]
For some reason [js2-highlight-vars](https://github.com/unhammer/js2-highlight-vars.el) does not pick up on the JSX tag names. E.g.,

```jsx
import Component from 'abc';

const c = () => (
    <Component/>
);
```

With point at the second `Component`, `js2-highlight-vars` does not highlight anything. Calling `js2-node-at-point` returns an `rjsx-member` rather than a `js2-name` node

**Comment by wyuenho** [comment]
@felipeochoa The tests for this seems to be completely broken again. I haven't figure out why yet, but it seems to be `rjsx-serialize-ast` is broken due to recent changes in js2-mode or Emacs 26.

**Comment by felipeochoa** [comment]
Gah. Thanks for letting me know. Is the issue with the highlighting too or just with the tests? If this is blocking the other PR feel free to disable these tests (mark as expected failure) and push on.

**Comment by wyuenho** [comment]
Ahh I think it's because `js2-node-short-name` is broken on Emacs 26. The first element of Emacs 26 cl-structs aren't prefixed with `cl-struct-` anymore.
