### ISSUE TITLE
can't type closing curly bracket (in combination with autopair-mode)

### ISSUE THREAD

**Issue by dfrkp** [felipeochoa/rjsx-mode#56]
Sorry to report another bug that only seems to surface in a certain configuration. Here's how it can be reproduced:
```
(load-file "~/.emacs.d/elpa/js2-mode-20171014.1229/js2-mode.el")
(load-file "~/.emacs.d/elpa/rjsx-mode-20171025.1621/rjsx-mode.el")
(load-file "~/.emacs.d/elpa/autopair-20160304.437/autopair.el")
```
Open a file with this content (in rjsx-mode with autpair-mode enabled)
```
class ShoppingList extends Component {
  render() {
    return (
      <div className="shopping-list">
	<h1>Shopping list for {this.props.name </h1></div>
  }
}
```
(note: I am aware of the missing `)`, but this bug basically forces a certain order in which to fix the parentheses.)
Attempt to type the closing curly bracket and get the error:
```
js2-mode-forward-sexp: Args out of range: #<buffer App.jsx>, 158, 688 [4 times]
```
Issue only occurs with rjsx-mode. js2-jsx-mode does not show the same problem.

**Comment by felipeochoa** [comment]
Keep them coming! I couldn't get to the bottom of this, but it's related to the rather hacky way that `rjsx` deals with unbalanced JSX brackets and missing tags. (It's really hard to recover from these errors). I tidied up a bit (there's still more to do), and that seems to have fixed the issue

**Comment by bearguns** [comment]
I'm experiencing the same issue using `rjsx-mode` in conjunction with `autopair-mode` in a React file. Would love to know if there's a way I can fix it!

**Comment by felipeochoa** [comment]
@bearguns Please open a new issue for this with the version of rjsx, Emacs, and js2 you're using, and a sample file for reproducing.
