### ISSUE TITLE
Support for the React’s new fragment syntax

### ISSUE THREAD

**Issue by mostafah** [felipeochoa/rjsx-mode#58]
React [introduced fragments recently](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html), along with a new JSX syntax for it: empty tags (`<>` and `</>`) are valid now. Its only difference with normal tags is that it does not accept any attributes. Support for this new syntax is being added to different tools and editors. It would be nice if `rjsx-mode` could support it too.

**Comment by felipeochoa** [comment]
Thanks -- I hadn't seen that. It should not be too challenging to add, but isn't a high priority right now. If anyone wants to send a PR, I'll gladly review/offer guidance, but won't to get to it myself before the end of the year, unfortunately

**Comment by mostafah** [comment]
I would work on this if I had any elisp experience. Nevertheless, I might try if I find time for it before you do.
