### ISSUE TITLE
[feature request] expand-region support for Tags

### ISSUE THREAD

**Issue by jbharat** [felipeochoa/rjsx-mode#59]
Is it possible to support expand-region in html tags of react. Right now if I try using expand-region on js functions it works well, even within the attributes(render props). But as soon as it sees a react tag, it selects the entire code in render return. 

~~Expand-region has support for html-mode~~ but I am not sure how to add that to rjsx-mode. 
expand-region not working on html mode as well. 
I am using rjsx-mode with spacemacs.

**Comment by jbharat** [comment]
this can be fixed with the below code.

```
  (defun er/add-html-expansions ()
    (make-variable-buffer-local 'er/try-expand-list)
    (setq er/try-expand-list (append
                              er/try-expand-list
                              '(er/mark-html-attribute
                              er/mark-inner-tag
                              er/mark-outer-tag))))

  (add-hook 'rjsx-mode-hook 'er/add-html-expansions)
```

I think this can be part of rjsx-mode.

**Comment by felipeochoa** [comment]
Thanks for the issue and the code! If you can put this in a PR with a couple of tests I'll merge it in. As an FYI for the tests, you'll have to add the install code for expand-region to the Makefile

**Comment by jbharat** [comment]
Behavior of using the above code is not consistent. It doesn't behave the way it should every time. I am not sure what is causing it to be inconsistent.

**Comment by felipeochoa** [comment]
Hmm that's annoying. I suppose we could write some custom functions using the AST if all else fails, but it would be nicer to get this simple solution working. What sort of inconsistencies are you observing?

**Comment by jbharat** [comment]
The goal is to incrementally select react components. The above code works sometimes. But sometimes it works only on the attributes and then directly selects all the components within the render function.
