### ISSUE TITLE
Wrong jsx tag alignement

### ISSUE THREAD

**Issue by othierry** [felipeochoa/rjsx-mode#60]
I am having troubles with jsx tags alignement when they span on multiple lines. (the bug is still present on `js2-jsx-mode` but works fine on mods like `web-mode`). 

Fore example, while most linters will expect:

```jsx
const Example = () => (
  <div>
    <Something
      attr="value"
      attr2="value"
    />
  </div>
)
```

I get the following indentation
```jsx
const Example = () => (
  <div>
    <Something
      attr="value"
      attr2="value"
      />
  </div>
)
```

I get the same results for non self-closing tags

Expected:
```jsx
const Example = () => (
  <div>
    <Something
      attr="value"
      attr2="value"
    >
      Content
    </Something>
  </div>
)
```

Result:
```jsx
const Example = () => (
  <div>
    <Something
      attr="value"
      attr2="value"
      >
      Content
    </Something>
  </div>
)
```

If it's by design, maybe we could make this customizable?

**Comment by felipeochoa** [comment]
Hi @othierry. This is a common request, but unfortunately, `rjsx` does not handle indentation. See #35 for a workaround

**Comment by othierry** [comment]
Hi @felipeochoa 
Ok thanks for the quick reply. 
There's also a workaround that worked perfectly for me using a `defadvice`: https://emacs.stackexchange.com/questions/33536/how-to-edit-jsx-react-files-in-emacs
