### ISSUE TITLE
Add face for brackets < and >

### ISSUE THREAD

**Issue by Fuco1** [felipeochoa/rjsx-mode#61]
In `web-mode` there is a face `web-mode-html-tag-bracket-face` for brackets.  I'm trying to configure `rjsx` to look the same so that I have consistency across the modes/buffers.

Would this be something simple to do?

**Comment by felipeochoa** [comment]
Done. Use `rjsx-tag-bracket-face`

**Comment by Fuco1** [comment]
Thanks that was quick! :heart:
