### ISSUE TITLE
Add styled-components syntax

### ISSUE THREAD

**Issue by jamestthompson3** [felipeochoa/rjsx-mode#63]
It would be nice to have support for writing CSS in JS syntax support for using libraries like [styled-components](https://www.styled-components.com/).

**Comment by felipeochoa** [comment]
I'm not familiar with that library. What would this support entail?

**Comment by jamestthompson3** [comment]
Basically it would involved recognizing that when the styled function is called, all of it's parameters should have CSS syntax.
e.g.
```js
const StyledButton = styled.button`
  background: transparent;
  border: 2px solid red;
  border-radius: 3px;
`
```

In this example, the `button` method is being called from the `styled` object. This function receives parameters like `background`, `border`, and `border-radius` that should have CSS syntax styling.

**Comment by felipeochoa** [comment]
Hmm that seems out of scope for this mode, which is focused purely on JSX functionality. If I understand correctly, this doesn't even depend on JSX.

If you're interested in pursuing this path, I think you could either extend the `js2` parser to handle template literals differently, or you could try to use one of the [multiple mode implementations](https://www.emacswiki.org/emacs/MultipleModes).

I'd be willing to provide some pointers regarding the `js2` parser and AST, and even add a couple hooks for `rjsx` if you or someone else writes an extension of `rjsx` to handle these templates, but I don't think this is the right place to have this functionality.
