### ISSUE TITLE
can't use rjsx-delete-creates-full-tag in other modes (typescript-mdoe for tsx)

### ISSUE THREAD

**Issue by yqrashawn** [felipeochoa/rjsx-mode#65]
`(get-char-property (point) 'rjsx-class)` here https://github.com/felipeochoa/rjsx-mode/blob/master/rjsx-mode.el#L900  
always return `nil` when `rjsx-mode` is off. Is it possible to use `rjsx-delete-creates-full-tag` in other major-mode?

**Comment by felipeochoa** [comment]
Unfortunately not. This property is set during parse, and that requires that rjsx-mode be enabled
