### ISSUE TITLE
Different (incorrect) indent behaviour from js2-jsx-mode

### ISSUE THREAD

**Issue by tarka** [felipeochoa/rjsx-mode#67]
I've noted the comment about indentation bugs, however I'm seeing a behaviour in rjsx-mode that this not present in js2.

In js2-jsx-mode the following code is formatted correctly:

```js
function Example(props) {
  return (
    <ul>
      {
        [1,2,3].map(lang => {
          return(
            <li key={lang}>
              {lang}
            </li>
          )
        })
      }
    </ul>
  )
}
```

However, in rjsx-mode it is formatted as:

```js
function Example(props) {
  return (
    <ul>
      {
        [1,2,3].map(lang => {
          return(
            <li key={lang}>
              {lang}
            </li>
          )
        })
    }
    </ul>
  )
}
```

(note the brace before the `</ul>`).

Versions:
* js2-mode-20180301
* rjsx-mode-20180314.845 and rjsx-mode-0.4.0

**Comment by felipeochoa** [comment]
Thanks for reporting (and taking the time to check against `js2-jsx`)! This was in fact a bug in `rjsx`. Fix will be up on Melpa soon
