### ISSUE TITLE
Support highligthing for gql tags

### ISSUE THREAD

**Issue by ar1a** [felipeochoa/rjsx-mode#69]
Support highlighting for stuff like
```
gql`
{
  test {
    id
  }
}
`
```
here's a picture off google of an example in vscode
https://user-images.githubusercontent.com/760112/34255465-d20b6800-e676-11e7-88ef-0ef65d6b95e9.png

yet in rjsx-mode etc it just displays as a string.

**Comment by felipeochoa** [comment]
While I think this is a worthwhile feature to have, I think this is out of scope for `rjsx`.
