### ISSUE TITLE
Parsing error on Windows

### ISSUE THREAD

**Issue by ryuslash** [felipeochoa/rjsx-mode#78]
Recently I've run into an issue where some files produce no syntax highlighting and show the following error:

```
Error running timer ‘js2-mode-idle-reparse’: (wrong-type-argument js2-node [cl-struct-js2-string-node 41 71 5 nil nil "bar"])
```

This is a small example that produced this particular error:

```jsx
function foo () {
  return (
    <div foo="bar"/>
  );
}
```

This doesn't occur when using `js2-jsx-mode`.

I'm running "GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30" installed through MSYS2 on Windows 10.

**Comment by felipeochoa** [comment]
Could this be the same as #77? Did you try the resolution there? I don't think there's anything linux/windows specific about rjsx

**Comment by ryuslash** [comment]
Ah, I should've looked more closely at the existing issues, I didn't find it. Yes deleting and reinstalling `rjsx-mode` fixed the problem!

Sorry for the noise and thanks!
