### ISSUE TITLE
disable highlighting the "test" and "expect" keywords in unit tests

### ISSUE THREAD

**Issue by lacker** [felipeochoa/rjsx-mode#80]
Hi, rjsx-mode is awesome and I really appreciate it. There is one thing that is slightly bugging me - I am using jest which adds `test` and `expect` in the global scope. In my unit test files, rjsx-mode is highlighting those words as if they are referring to an undefined entity. Is there a way to turn off this highlighting?

**Comment by felipeochoa** [comment]
You should look at the docstring `js2-additional-externs` which describes all your options. 

The easiest way if you don't mind the noise is to add this to the top of your file:

```js
/*global describe, it, test, expect, beforeEach, afterEach, beforeAll, afterAll, fail, jest */
```

**Comment by lacker** [comment]
Thank you very much! I really appreciate it.
