### ISSUE TITLE
multiline jsx element indentation issue

### ISSUE THREAD

**Issue by DeeeeLAN** [felipeochoa/rjsx-mode#94]
If I have a react element such as this:

```
<XAxis                                                                  
    axisAt="bottom"                                         
    orient="bottom"                                        
    innerTickSize={-1 * 400}                               
    tickStrokeDasharray='Solid'                            
    tickStrokeOpacity={0.2}                                
    tickStrokeWidth={1}                                    
/>  
```

indentation doesn't work reliably on the properties. Sometimes it indents them to the correct location, but sometimes it does nothing and gives the error "Symbol's value as variable is void: sgml-attribute-offset". js2-jsx-mode does indent them, but not to the proper location. 

Equally frustrating (and I think related, it gives the same error): When typing one of those properties, as soon as I type the opening bracket: {, the screen flashes and moves the cursor to the beginning of the line.

**Comment by DeeeeLAN** [comment]
I tried removing the 'sgml-attribute-offset' from #L1396 and so for that seems to have helped. Not sure if the issue is completely gone yet, or if I caused other issues by removing that.

**Comment by darkleaf** [comment]
+1
