### ISSUE TITLE
Any love for decorators

### ISSUE THREAD

**Issue by tavurth** [felipeochoa/rjsx-mode#95]
I really want to use js2 or rjsx mode, but since my company uses decorators pretty heavily it's hard.
Any way I could create a workaround for decorator styling?

<img width="755" alt="screenshot 2019-02-13 at 10 42 02 am" src="https://user-images.githubusercontent.com/100964/52685395-25509900-2f7c-11e9-825e-56d1bb8809d5.png">

**Comment by felipeochoa** [comment]
Your best bet would be to add them to the js2 parser. I can't imagine it's
terribly hard given there's already support for the get/set keywords.
