### ISSUE TITLE
start with rjsx-mode

### ISSUE THREAD

**Issue by blutics** [felipeochoa/rjsx-mode#96]
is there any way to start js files with rjsx mode??

**Comment by felipeochoa** [comment]
You can either use `auto-mode-alist` or set a file local `mode` variable

**Comment by Chipe1** [comment]
As @felipeochoa mentioned, just add the line `(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))` to your .emacs or init.el file.
