### ISSUE TITLE
Error in menu-bar-update-hook

### ISSUE THREAD

**Issue by FabriceSalvaire** [felipeochoa/rjsx-mode#97]
I got this error after to update all packages

`Error in menu-bar-update-hook (imenu-update-menubar): (wrong-type-argument js2-node [cl-struct-js2-string-node 41 1879 14 nil nil "FOO-BAR"])`

Foo-Bar comes from `<div className="FOO-BAR">`

and code is not highlighted.

**Comment by felipeochoa** [comment]
Can you reproduce in a fresh Emacs session? Looks like an issue with the
upgrade

**Comment by FabriceSalvaire** [comment]
yes I can reproduce it. I don't know where it comes from, I tried to downgrade js2-mode but it doesn't solve this issue.

**Comment by FabriceSalvaire** [comment]
fixed using (byte-recompile-directory "~/.emacs.d/" nil 'force)
