### ISSUE TITLE
invalid JSX identifier

### ISSUE THREAD

**Issue by knobo** [felipeochoa/rjsx-mode#98]
Why is `in` an invalid attribute?
``` js
function Mytag (props) {
  return (
  <CSSTransition
      in={ toggleState }
    >
  </CSSTransition>);
}
```

![invalid-jsx-identiier](https://user-images.githubusercontent.com/89921/53993938-0e433800-4131-11e9-9b8f-a31e496cb52e.png)

**Comment by felipeochoa** [comment]
It's a keyword. See #62
